## Tensors
### このスクリプトでは、TensorFlowでテンソルを作成するさまざまな方法を紹介します
最初に、TensorFlowを読み込み、計算グラフをリセットすることから始めます。

In [ ]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

### グラフセッションを開始する
tf.Session（）でグラフハンドルを取得する

In [2]:
sess = tf.Session()

### テンソルの作成
TensorFlowには、変数で使用するテンソルを作成する関数が組み込まれています。たとえば、次のようにtf.zeros（）関数を使用して、事前定義された形状のゼロ充填テンソルを作成できます。

In [7]:
my_tensor = tf.zeros([1,20])

セッションでrun（）メソッドを呼び出すと、テンソルを評価できます。

In [4]:
sess.run(my_tensor)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

TensorFlowアルゴリズムは、どのオブジェクトが変数であり、どのオブジェクトが定数であるかを知る必要があります。これらの2つのオブジェクトの違いについては、この章の後半で説明します。ここでは、次のようにTensorFlow関数tf.Variable（）を使用して変数を作成します。

In [5]:
my_var = tf.Variable(tf.zeros([1,20]))

sess.run（my_var）を実行できないことに注意してください。これによりエラーが発生します。 TensorFlowは計算グラフで動作するため、変数を評価するためには変数の初期化操作を作成する必要があります。これについては後で詳しく説明します。このスクリプトでは、変数メソッドmy_var.initializerを呼び出すことで、一度に1つの変数を初期化できます。

In [6]:
sess.run(my_var.initializer)
sess.run(my_var)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

行と列のサイズを宣言して、特定の形状の変数を作成してみましょう。

In [8]:
row_dim = 2
col_dim = 3

ここには、すべての0または1を含むように初期化された変数があります。

In [9]:
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))

ここでも、変数に対してイニシャライザメソッドを呼び出し、実行してその内容を評価することができます。

In [10]:
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
print(sess.run(zero_var))
print(sess.run(ones_var))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]


### 他のテンソルの形状に基づくテンソルの作成
テンソルの形状が別のテンソルの形状に依存する場合は、TensorFlow組み込み関数ones_like（）またはzeros_like（）を使用できます。

In [11]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(ones_similar.initializer)
sess.run(zero_similar.initializer)
print(sess.run(ones_similar))
print(sess.run(zero_similar))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


### テンソルを定数で埋める
テンソルを定数で満たす方法は次のとおりです

In [12]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
sess.run(fill_var.initializer)
print(sess.run(fill_var))

[[-1 -1 -1]
 [-1 -1 -1]]


また、配列や定数のリストから変数を作成することもできます。

In [13]:
# Create a Variable from a constant
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
# This can also be used to fill an array:
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[8 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


### シーケンスと範囲に基づくテンソルの作成
TensorFlowではシーケンス生成関数からテンソルを作成することもできます。 TensorFlow関数linspace（）とrange（）は、同等のpython / numpyと非常によく似ています。

In [14]:
# Linspace in TensorFlow
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3)) # Generates [0,0, 0.5, 1.0] includes the end

# Range in TensorFlow
sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3)) # Generates [6, 9, 12] doesn't include the end

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)

print(sess.run(linear_var))
print(sess.run(sequence_var))

[ 0.   0.5  1. ]
[ 6  9 12]


### ランダム数テンソル
また、次のような乱数から生じるテンソルを初期化することもできます。

In [15]:
rnorm_var = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=1.0)
runif_var = tf.random_uniform([row_dim, col_dim], minval=0, maxval=4)

print(sess.run(rnorm_var))
print(sess.run(runif_var))

[[ 1.30184519  0.63802606 -0.04424106]
 [-0.67636484 -0.65225536  1.0798924 ]]
[[ 1.1475563   0.05278111  1.88548756]
 [ 2.06054401  0.99945307  1.04309511]]


### TensorBoardでの変数作成の可視化
Tensorboardで変数の作成を視覚化するには（第11章で詳しく説明します）、計算グラフをリセットしてグローバルな初期化操作を作成します。

In [17]:
# Reset graph
ops.reset_default_graph()

# Strat a graph session
sess = tf.Session()

# Create variable
my_var = tf.Variable(tf.zeros([1,20]))

# Add summarise to tensorboard
merged = tf.summary.merge_all()

# Initialize graph writer:
writer = tf.summary.FileWriter("/tmp/variable_logs", graph=sess.graph)

# Initialize operation
initialize_op = tf.global_variables_initializer()

# Run initialization of variable
sess.run(initialize_op)