## プレースホルダ
TensorFlowでプレースホルダを使用する方法を紹介します。  
最初に必要なライブラリをインポートし、グラフセッションをリセットします。

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

グラフセッションを開始します。

In [2]:
sess = tf.Session()

### プレースホルダを宣言する
TensorFlowの関数tf.placeholder（）を使用して、データ型引数（tf.float32）と形状引数（4,4）を受け取るプレースホルダを宣言します。形状はタプルまたはリスト[4,4]にすることができます。

In [3]:
x = tf.placeholder(tf.float32, shape=(4, 4))

プレースホルダの使い方については、そのプレースホルダの入力データとTensorboardで視覚化できる操作を作成します。  
feed_dictの使用に注意してください。ここでは、xの値を計算グラフに送ります。

In [4]:
# Input data to placeholder. note that 'rand_array' and 'x' are the same shape.
rand_array = np.random.rand(4, 4)

# Create a Tensor to perform an operation (here, y will be equal to x, a 4x4 matrix(x))
y = tf.identity(x)

# Print the output, feeding the value of x into computational graph
print(sess.run(y, feed_dict={x: rand_array}))

[[ 0.58151072  0.34176034  0.06961016  0.02569318]
 [ 0.54335523  0.48827365  0.59535074  0.09259212]
 [ 0.72202748  0.36466759  0.43397471  0.54621112]
 [ 0.43325529  0.85063809  0.7165463   0.67005324]]


Tensorboardでこれを視覚化するために、要約をマージしてログファイルに書き込みます。

In [5]:
merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("/tmp/variable_logs", sess.graph)

プロンプトで次のコマンドを実行します  
tensorboard --logdir=/tmp  
計算グラフを視覚化するためにクロムをどこにナビゲートするかがわかります。デフォルトは  
http://0.0.0.0:6006/