In [2]:
import tensorflow as tf
import numpy as np

sess = tf.Session()

In [3]:
data_size = 25
# 1次元のデータを生成
data_1d = np.random.normal(size=data_size)
# プレースホルダを作成
x_input_1d = tf.placeholder(dtype=tf.float32, shape=[data_size])

In [4]:
def conv_layer_1d(input_1d, my_filter):
    # 1次元の入力を4次元にする
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    # ストライド1で畳み込みを実行
    convolution_output = tf.nn.conv2d(input_4d, filter=my_filter, strides=[1,1,1,1], padding="VALID")
    # 余分な次元を削除
    conv_output_1d = tf.squeeze(convolution_output)
    return(conv_output_1d)

In [5]:
my_filter = tf.Variable(tf.random_normal(shape=[1,5,1,1]))
my_convolution_output = conv_layer_1d(x_input_1d, my_filter)

In [9]:
def  activation(input_1d):
    return(tf.nn.relu(input_1d))

# 活性化層を作成
my_activation_output = activation(my_convolution_output)

In [11]:
def max_pool(input_1d, width):
    # 1次元の入力を4次元にする
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    # ストライド1でマックスプーリンを実行
    pool_output = tf.nn.max_pool(input_4d, ksize=[1, 1, width, 1], strides=[1, 1, 1, 1], padding="VALID")
    # 余分な次元を削除
    pool_output_1d = tf.squeeze(pool_output)
    return(pool_output_1d)

# マックスプーリング層を作成
my_maxpool_output = max_pool(my_activation_output, width=5)

In [12]:
def fully_connected(input_layer, num_outputs):
    # 重みを作成
    weight_shape = tf.squeeze(tf.stack([tf.shape(input_layer), [num_outputs]]))
    # 重みを初期化
    weight = tf.random_normal(weight_shape, stddev=0.1)
    # バイアスを初期化
    bias = tf.random_normal(shape=[num_outputs])
    # 入力を2次元配列にする
    input_layer_2d = tf.expand_dims(input_layer, 0)
    # 全結合演算（行列の乗算とバイアスの追加）を実行
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    # 余分な次元を削除
    full_output_1d = tf.squeeze(full_output)
    return(full_output_1d)

# 全結合層を作成
my_full_output  = fully_connected(my_maxpool_output, 5)

In [13]:
init = tf.global_variables_initializer()
sess.run(init)

feed_dict = {x_input_1d: data_1d}

In [14]:
# 畳み込み層の出力
print('Input = array of length 25')
print('Convolution w/filter, length = 5, stride size = 1, results in an array of length 21:')
print(sess.run(my_convolution_output, feed_dict=feed_dict))

# 活性化層の出力
print('¥nInput = the above array of length 21')
print('ReLU element wise returns the array of length 21:')
print(sess.run(my_activation_output, feed_dict=feed_dict))

# マックスプーリング層の出力
print('¥nInput = the above array of length 21')
print('MaxPool, window length = 5, stride size = 1, results in the array of length 17')
print(sess.run(my_maxpool_output, feed_dict=feed_dict))

# 全結合層への出力
print('¥nInput = the above array of length 17')
print('Fully connnected layer on all four rows with five outputs:')
print(sess.run(my_full_output, feed_dict=feed_dict))

Input = array of length 25
Convolution w/filter, length = 5, stride size = 1, results in an array of length 21:
[-1.05097878 -0.30860162  0.09815298 -0.35026589 -0.84521806  1.70141625
 -0.29660401  2.65369606  0.77026397  0.13656747  1.08798301 -2.41421509
  1.12136614 -2.98701859  1.14287055 -0.67281902  1.08716643 -1.01938283
  0.70333934 -2.74435186 -0.65808177]
¥nInput = the above array of length 21
ReLU element wise returns the array of length 21:
[ 0.          0.          0.09815298  0.          0.          1.70141625
  0.          2.65369606  0.77026397  0.13656747  1.08798301  0.
  1.12136614  0.          1.14287055  0.          1.08716643  0.
  0.70333934  0.          0.        ]
¥nInput = the above array of length 21
MaxPool, window length = 5, stride size = 1, results in the array of length 17
[ 0.09815298  1.70141625  1.70141625  2.65369606  2.65369606  2.65369606
  2.65369606  2.65369606  1.12136614  1.12136614  1.14287055  1.14287055
  1.14287055  1.14287055  1.14287055 

In [16]:
from tensorflow.python.framework import ops
ops.reset_default_graph()
sess = tf.Session()

In [17]:
data_size = [10,10]
# 2次元のデータを生成
data_2d = np.random.normal(size=data_size)
# プレースホルダを作成
x_input_2d = tf.placeholder(dtype=tf.float32, shape=data_size)

In [18]:
def conv_layer_2d(input_2d, my_filter):
    # 2次元の入力を4次元にする
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    # 畳み込みを実行（ストライドの違いに注意）
    convolution_output = tf.nn.conv2d(input_4d, filter=my_filter, strides=[1,2,2,1], padding="VALID")
    # 余分な次元を削除
    conv_output_2d = tf.squeeze(convolution_output)
    return(conv_output_2d)

# 畳み込みフィルタを作成
my_filter = tf.Variable(tf.random_normal(shape=[2,2,1,1]))
# 畳み込み層を作成
my_convolution_output = conv_layer_2d(x_input_2d, my_filter)

In [19]:
def activation(input_2d):
    return(tf.nn.relu(input_2d))

# 活性化層を作成
my_activation_output = activation(my_convolution_output)

In [21]:
def max_pool(input_2d, width, height):
    # 2次元の入力を4次元にする
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    # マックスプーリングを実行
    pool_output = tf.nn.max_pool(input_4d, ksize=[1, height, width, 1], strides=[1, 1, 1, 1], padding='VALID')
    # 余分な次元を削除
    pool_output_2d = tf.squeeze(pool_output)
    return(pool_output_2d)

# マックスプーリング層を作成
my_maxpool_output = max_pool(my_activation_output, width=2, height=2)

In [26]:
def fully_connected(input_layer, num_outputs):
    # 1次元にする
    flat_input = tf.reshape(input_layer, [-1])
    # 重みを作成
    weight_shape = tf.squeeze(tf.stack([tf.shape(flat_input), [num_outputs]]))
    # 重みを初期化
    weight = tf.random_normal(weight_shape, stddev=0.1)
    # バイアスを初期化
    bias = tf.random_normal(shape=[num_outputs])
    # 2次元にする
    input_2d = tf.expand_dims(flat_input, 0)
    # 全結合演算を実行
    full_output = tf.add(tf.matmul(input_2d, weight), bias)
    # 余分な次元を削除
    full_output_2d = tf.squeeze(full_output)
    return(full_output_2d)

#全結合層を作成
my_full_output = fully_connected(my_maxpool_output, 5)

In [27]:
init = tf.global_variables_initializer()
sess.run(init)

feed_dict = {x_input_2d: data_2d}

In [28]:
# 畳み込み層の出力
print('Input = [10,10] array')
print('[2, 2] Convolution, stride size = [2, 2], results in the [5, 5] array')
print(sess.run(my_convolution_output, feed_dict=feed_dict))
# 活性化層の出力
print('¥nInput = the above [5, 5] array')
print('ReLU element wise returns the [5, 5] array')
print(sess.run(my_activation_output, feed_dict=feed_dict))
#マックスプーリング層の出力
print('¥nInput = the above [5, 5] array')
print('MaxPool, stride size = [1, 1], results in the [4, 4] array')
print(sess.run(my_maxpool_output, feed_dict=feed_dict))
# 全結合層の出力
print('¥nInput = the above [4, 4] array')
print('Fully connected layer on all 4 rows results in 5 outputs:')
print(sess.run(my_full_output, feed_dict=feed_dict))

Input = [10,10] array
[2, 2] Convolution, stride size = [2, 2], results in the [5, 5] array
[[ 2.66505671  2.94650412 -1.06595957 -0.53130883 -1.55073035]
 [ 1.76208854 -0.11624587  0.48761457 -0.08125717 -0.05775905]
 [-2.07696009  0.95554638 -0.13551201  0.44764209 -0.08830321]
 [ 0.57219076  1.04545355  1.43570781 -0.48084152  1.78725421]
 [-0.24305016  1.8197875  -0.80240077 -0.38667798  0.35234463]]
¥nInput = the above [5, 5] array
ReLU element wise returns the [5, 5] array
[[ 2.66505671  2.94650412  0.          0.          0.        ]
 [ 1.76208854  0.          0.48761457  0.          0.        ]
 [ 0.          0.95554638  0.          0.44764209  0.        ]
 [ 0.57219076  1.04545355  1.43570781  0.          1.78725421]
 [ 0.          1.8197875   0.          0.          0.35234463]]
¥nInput = the above [5, 5] array
MaxPool, stride size = [1, 1], results in the [4, 4] array
[[ 2.94650412  2.94650412  0.48761457  0.        ]
 [ 1.76208854  0.95554638  0.48761457  0.44764209]
 [ 1.0